╔════════════════════════════════════════════════════════╗
║             💎  SUPPORT SECURE-DELETE  💎             ║
║    "Because some data deserves a dignified death."     ║
║                                                        ║
║                        github.com/sponsors/whisprer    ║
╚════════════════════════════════════════════════════════╝
