---

<p align="center">
  <img src="https://raw.githubusercontent.com/whisprer/Secure-Delete/main/assets/logo_shredder.png" width="128" alt="Secure-Delete logo"/>
</p>

<h3 align="center">💎 Support Secure-Delete 💎</h3>

<p align="center">
  <em>“Because some data deserves a dignified death.”</em>
</p>

<p align="center">
  <a href="https://github.com/sponsors/whisprer">
    <img src="https://img.shields.io/badge/Sponsor_on_GitHub-%2300A3E0.svg?style=for-the-badge&logo=githubsponsors&logoColor=white" alt="Sponsor on GitHub"/>
  </a>
</p>

<p align="center">
  <sub>
    Your support keeps <strong>Secure-Delete</strong> free, fast, and cross-platform.<br/>
    Every byte securely shredded brings us closer to digital peace of mind.
  </sub>
</p>

---
